//
// Created by 陈思言 on 2021/7/8.
//

#include "CodeSectionGenerator.h"

CodeSectionGenerator::CodeSectionGenerator() {
    textSection << "\t.text\n";
    textSection << "\t.arch armv7ve\n";
//    textSection << "\t.arch armv7-a\n";
//    textSection << "\t.arch_extension virt\n";
//    textSection << "\t.arch_extension idiv\n";
//    textSection << "\t.arch_extension sec\n";
//    textSection << "\t.arch_extension mp\n";
}

void CodeSectionGenerator::addFunction(Function &fn, stringstream &body) {
    auto name = fn.getName();
    textSection << '\n';
    textSection << "\t.align 3\n";
    textSection << "\t.global " << name << '\n';
    textSection << "\t.type " << name << ", %function\n";
    textSection << name << ":\n";
    textSection << "\t@ args = " << fn.args.size() << '\n';
    textSection << body.str();
    textSection << "\t.size " << name << ", .-" << name << '\n';
    body.str("");
}

void CodeSectionGenerator::createThreadPool() {
    textSection <<
                "\t.align	3\n"
                "\t.global	wake_up\n"
                "\t.type	wake_up, %function\n"
                "wake_up:\n"
                "\tbx	lr\n"
                "\t.size	wake_up, .-wake_up\n"
                "\t\n"
                "\t.align	3\n"
                "\t.global	notifyOneWorker\n"
                "\t.type	notifyOneWorker, %function\n"
                "notifyOneWorker:\n"
                "\tmovw	r3, #:lower16:workerThreads\n"
                "\tmovt	r3, #:upper16:workerThreads\n"
                "\tldr	r2, [r3, #4]\n"
                "\tcmp	r2, #0\n"
                "\tbeq	.L4\n"
                "\tldr	r2, [r3, #12]\n"
                "\tcmp	r2, #0\n"
                "\tbeq	.L6\n"
                "\tldr	r2, [r3, #20]\n"
                "\tcmp	r2, #0\n"
                "\tmoveq	r2, #2\n"
                "\tbxne	lr\n"
                ".L4:\n"
                "\tldr	r0, [r3, r2, lsl #3]\n"
                "\tmov	r1, #10\n"
                "\tb	kill\n"
                ".L6:\n"
                "\tmov	r2, #1\n"
                "\tb	.L4\n"
                "\t.size	notifyOneWorker, .-notifyOneWorker\n"
                "\t\n"
                "\t.align	3\n"
                "\t.global	getTask\n"
                "\t.type	getTask, %function\n"
                "getTask:\n"
                "\tpush	{r4, r5, r6, r7, r8, lr}\n"
                "\tsub	sp, sp, #256\n"
                "\tmov	r5, r0\n"
                "\tmovw	r4, #:lower16:queueInfo\n"
                "\tmov	r0, sp\n"
                "\tmovt	r4, #:upper16:queueInfo\n"
                "\tbl	sigemptyset\n"
                "\tmov	r1, #10\n"
                "\tmov	r0, sp\n"
                "\tbl	sigaddset\n"
                "\tadd	r2, sp, #128\n"
                "\tmov	r1, sp\n"
                "\tmov	r0, #0\n"
                "\tbl	sigprocmask\n"
                "\tmov	r0, r4\n"
                "\tbl	wait_spin_lock\n"
                "\tldr	r2, [r4, #8]\n"
                "\tldr	r3, [r4, #12]\n"
                "\tcmp	r2, r3\n"
                "\tbne	.L12\n"
                "\tmov	r6, #0\n"
                "\tmov	r8, #1\n"
                "\tmov	r7, r4\n"
                ".L13:\n"
                "\tstr	r6, [r4]\n"
                "\tadd	r0, sp, #128\n"
                "\tstr	r6, [r5, #4]\n"
                "\tbl	sigsuspend\n"
                "\tstr	r8, [r5, #4]\n"
                "\tmov	r0, r7\n"
                "\tbl	wait_spin_lock\n"
                "\tldr	r2, [r4, #8]\n"
                "\tldr	r3, [r4, #12]\n"
                "\tcmp	r2, r3\n"
                "\tbeq	.L13\n"
                ".L12:\n"
                "\tadd	r1, sp, #128\n"
                "\tmov	r2, #0\n"
                "\tmov	r0, #2\n"
                "\tbl	sigprocmask\n"
                "\tldr	r1, [r4, #8]\n"
                "\tldr	r2, [r4, #8]\n"
                "\tmovw	r3, #:lower16:taskQueue\n"
                "\tmovt	r3, #:upper16:taskQueue\n"
                "\tadd	r2, r3, r2, lsl #3\n"
                "\tldr	r0, [r3, r1, lsl #3]\n"
                "\tldr	r3, [r2, #4]\n"
                "\tsub	r3, r3, #1\n"
                "\tstr	r3, [r2, #4]\n"
                "\tcmp	r3, #0\n"
                "\tldreq	r3, [r4, #8]\n"
                "\taddeq	r3, r3, #1\n"
                "\tubfxeq	r3, r3, #0, #9\n"
                "\tstreq	r3, [r4, #8]\n"
                "\tmov	r3, #0\n"
                "\tstr	r3, [r4]\n"
                "\tadd	sp, sp, #256\n"
                "\tpop	{r4, r5, r6, r7, r8, pc}\n"
                "\t.size	getTask, .-getTask\n"
                "\t\n"
                "\t.align	3\n"
                "\t.global	workLoop\n"
                "\t.type	workLoop, %function\n"
                "workLoop:\n"
                "\tpush	{r4, r5, r6, lr}\n"
                "\tmov	r6, r0\n"
                "\tbl	getpid\n"
                "\tmov	r4, #1\n"
                "\tmovw	r1, #:lower16:wake_up\n"
                "\tstr	r4, [r6, #4]\n"
                "\tmovt	r1, #:upper16:wake_up\n"
                "\tstr	r0, [r6]\n"
                "\tmov	r0, #10\n"
                "\tbl	signal\n"
                "\tmovw	r1, #:lower16:wake_up\n"
                "\tmov	r0, #12\n"
                "\tmovt	r1, #:upper16:wake_up\n"
                "\tbl	signal\n"
                "\tmov	r0, r4\n"
                "\tmovw	r1, #:lower16:readyThreads\n"
                "\tmovt	r1, #:upper16:readyThreads\n"
                "\tbl	atomic_add\n"
                "\tcmp	r0, #3\n"
                "\tbeq	.L31\n"
                ".L18:\n"
                "\tmovw	r5, #:lower16:workerThreads\n"
                "\tmovt	r5, #:upper16:workerThreads\n"
                "\tb	.L22\n"
                ".L33:\n"
                "\tldr	r3, [r5, #12]\n"
                "\tcmp	r3, #0\n"
                "\tbeq	.L24\n"
                "\tldr	r3, [r5, #20]\n"
                "\tcmp	r3, #0\n"
                "\tmoveq	r3, #2\n"
                "\tbeq	.L19\n"
                "\tsubs	r0, r4, #0\n"
                "\tbeq	.L29\n"
                ".L34:\n"
                "\tldr	r3, [r4]\n"
                "\tblx	r3\n"
                "\tadd	r1, r4, #4\n"
                "\tmvn	r0, #0\n"
                "\tbl	atomic_add\n"
                "\tcmp	r0, #0\n"
                "\tbeq	.L32\n"
                ".L22:\n"
                "\tmov	r0, r6\n"
                "\tbl	getTask\n"
                "\tldr	r3, [r5, #4]\n"
                "\tcmp	r3, #0\n"
                "\tmov	r4, r0\n"
                "\tbne	.L33\n"
                ".L19:\n"
                "\tldr	r0, [r5, r3, lsl #3]\n"
                "\tmov	r1, #10\n"
                "\tbl	kill\n"
                ".L35:\n"
                "\tsubs	r0, r4, #0\n"
                "\tbne	.L34\n"
                ".L29:\n"
                "\tmov	r0, r4\n"
                "\tpop	{r4, r5, r6, pc}\n"
                ".L24:\n"
                "\tmov	r3, #1\n"
                "\tmov	r1, #10\n"
                "\tldr	r0, [r5, r3, lsl #3]\n"
                "\tbl	kill\n"
                "\tb	.L35\n"
                ".L32:\n"
                "\tldr	r0, [r4, #8]\n"
                "\tmov	r1, #12\n"
                "\tbl	kill\n"
                "\tb	.L22\n"
                ".L31:\n"
                "\tmovw	r3, #:lower16:main_pid\n"
                "\tmovt	r3, #:upper16:main_pid\n"
                "\tmov	r1, #12\n"
                "\tldr	r0, [r3]\n"
                "\tbl	kill\n"
                "\tb	.L18\n"
                "\t.size	workLoop, .-workLoop\n"
                "\t\n"
                "\t.align	3\n"
                "\t.global	addTask\n"
                "\t.type	addTask, %function\n"
                "addTask:\n"
                "\tpush	{r4, r5, r6, lr}\n"
                "\tsubs	r6, r0, #0\n"
                "\tmov	r5, r1\n"
                "\tbeq	.L37\n"
                "\tstr	r1, [r6, #4]\n"
                "\tbl	getpid\n"
                "\tstr	r0, [r6, #8]\n"
                ".L37:\n"
                "\tmovw	r4, #:lower16:queueInfo\n"
                "\tmovt	r4, #:upper16:queueInfo\n"
                "\tmov	r0, r4\n"
                "\tbl	wait_spin_lock\n"
                "\tldr	r2, [r4, #8]\n"
                "\tldr	r3, [r4, #12]\n"
                "\tadd	r3, r3, #1\n"
                "\tubfx	r3, r3, #0, #9\n"
                "\tcmp	r2, r3\n"
                "\tmoveq	r5, #0\n"
                "\tbeq	.L38\n"
                "\tldr	r1, [r4, #12]\n"
                "\tmovw	r3, #:lower16:taskQueue\n"
                "\tldr	r2, [r4, #12]\n"
                "\tmovt	r3, #:upper16:taskQueue\n"
                "\tstr	r6, [r3, r1, lsl #3]\n"
                "\tadd	r2, r3, r2, lsl #3\n"
                "\tstr	r5, [r2, #4]\n"
                "\tldr	r5, [r4, #12]\n"
                "\tldr	r2, [r4, #12]\n"
                "\tadd	r2, r2, #1\n"
                "\tadd	r5, r3, r5, lsl #3\n"
                "\tubfx	r3, r2, #0, #9\n"
                "\tstr	r3, [r4, #12]\n"
                ".L38:\n"
                "\tmovw	r3, #:lower16:workerThreads\n"
                "\tmovt	r3, #:upper16:workerThreads\n"
                "\tmov	r2, #0\n"
                "\tstr	r2, [r4]\n"
                "\tldr	r2, [r3, #4]\n"
                "\tcmp	r2, #0\n"
                "\tbeq	.L39\n"
                "\tldr	r2, [r3, #12]\n"
                "\tcmp	r2, #0\n"
                "\tbeq	.L42\n"
                "\tldr	r2, [r3, #20]\n"
                "\tcmp	r2, #0\n"
                "\tmoveq	r2, #2\n"
                "\tbeq	.L39\n"
                "\tmov	r0, r5\n"
                "\tpop	{r4, r5, r6, pc}\n"
                ".L42:\n"
                "\tmov	r2, #1\n"
                ".L39:\n"
                "\tldr	r0, [r3, r2, lsl #3]\n"
                "\tmov	r1, #10\n"
                "\tbl	kill\n"
                "\tmov	r0, r5\n"
                "\tpop	{r4, r5, r6, pc}\n"
                "\t.size	addTask, .-addTask\n"
                "\t\n"
                "\t.align	3\n"
                "\t.global	deleteTask\n"
                "\t.type	deleteTask, %function\n"
                "deleteTask:\n"
                "\tpush	{r4, r5, r6, lr}\n"
                "\tmovw	r4, #:lower16:queueInfo\n"
                "\tmovt	r4, #:upper16:queueInfo\n"
                "\tmov	r5, r0\n"
                "\tmov	r0, r4\n"
                "\tbl	wait_spin_lock\n"
                "\tldr	r1, [r5]\n"
                "\tldr	r0, [r5, #4]\n"
                "\tmov	r2, #0\n"
                "\tldr	r3, [r1, #4]\n"
                "\tsub	r3, r3, r0\n"
                "\tstr	r3, [r1, #4]\n"
                "\tstr	r2, [r5, #4]\n"
                "\tstr	r2, [r4]\n"
                "\tpop	{r4, r5, r6, pc}\n"
                "\t.size	deleteTask, .-deleteTask\n"
                "\t\n"
                "\t.align	3\n"
                "\t.global	waitTask\n"
                "\t.type	waitTask, %function\n"
                "waitTask:\n"
                "\tpush	{r4, lr}\n"
                "\tsub	sp, sp, #256\n"
                "\tmov	r4, r0\n"
                "\tmov	r0, sp\n"
                "\tbl	sigemptyset\n"
                "\tmov	r1, #12\n"
                "\tmov	r0, sp\n"
                "\tbl	sigaddset\n"
                "\tmov	r1, sp\n"
                "\tadd	r2, sp, #128\n"
                "\tmov	r0, #0\n"
                "\tbl	sigprocmask\n"
                "\tldr	r3, [r4, #4]\n"
                "\tcmp	r3, #0\n"
                "\tbeq	.L53\n"
                ".L54:\n"
                "\tadd	r0, sp, #128\n"
                "\tbl	sigsuspend\n"
                "\tldr	r3, [r4, #4]\n"
                "\tcmp	r3, #0\n"
                "\tbne	.L54\n"
                ".L53:\n"
                "\tadd	r1, sp, #128\n"
                "\tmov	r2, #0\n"
                "\tmov	r0, #2\n"
                "\tbl	sigprocmask\n"
                "\tadd	sp, sp, #256\n"
                "\tpop	{r4, pc}\n"
                "\t.size	waitTask, .-waitTask\n"
                "\t\n"
                "\t.align	3\n"
                "\t.global	initThreadPool\n"
                "\t.type	initThreadPool, %function\n"
                "initThreadPool:\n"
                "\tpush	{r4, r5, r6, r7, r8, lr}\n"
                "\tsub	sp, sp, #264\n"
                "\tbl	getpid\n"
                "\tmovw	r3, #:lower16:main_pid\n"
                "\tmovt	r3, #:upper16:main_pid\n"
                "\tmovw	r1, #:lower16:wake_up\n"
                "\tmovw	r4, #:lower16:workerThreads\n"
                "\tmovt	r1, #:upper16:wake_up\n"
                "\tmovt	r4, #:upper16:workerThreads\n"
                "\tmovw	r6, #8225\n"
                "\tmovw	r5, #:lower16:workLoop\n"
                "\tmovt	r6, 2\n"
                "\tadd	r8, r4, #24\n"
                "\tmovt	r5, #:upper16:workLoop\n"
                "\tmov	r7, #0\n"
                "\tstr	r0, [r3]\n"
                "\tmov	r0, #12\n"
                "\tbl	signal\n"
                ".L61:\n"
                "\tmvn	r2, #0\n"
                "\tmov	r3, r6\n"
                "\tstr	r2, [sp]\n"
                "\tmov	r1, #1048576\n"
                "\tmov	r2, #3\n"
                "\tstr	r7, [sp, #4]\n"
                "\tmov	r0, #0\n"
                "\tbl	mmap\n"
                "\tmov	r3, r4\n"
                "\tmovw	r2, #273\n"
                "\tadd	r4, r4, #8\n"
                "\tadd	r1, r0, #1048576\n"
                "\tmov	r0, r5\n"
                "\tbl	clone\n"
                "\tcmp	r4, r8\n"
                "\tbne	.L61\n"
                "\tadd	r0, sp, #8\n"
                "\tmovw	r4, #:lower16:readyThreads\n"
                "\tbl	sigemptyset\n"
                "\tmovt	r4, #:upper16:readyThreads\n"
                "\tmov	r1, #12\n"
                "\tadd	r0, sp, #8\n"
                "\tbl	sigaddset\n"
                "\tadd	r1, sp, #8\n"
                "\tadd	r2, sp, #136\n"
                "\tmov	r0, #0\n"
                "\tbl	sigprocmask\n"
                "\tldr	r3, [r4]\n"
                "\tcmp	r3, #3\n"
                "\tbeq	.L62\n"
                ".L63:\n"
                "\tadd	r0, sp, #136\n"
                "\tbl	sigsuspend\n"
                "\tldr	r3, [r4]\n"
                "\tcmp	r3, #3\n"
                "\tbne	.L63\n"
                ".L62:\n"
                "\tadd	r1, sp, #136\n"
                "\tmov	r2, #0\n"
                "\tmov	r0, #2\n"
                "\tbl	sigprocmask\n"
                "\tadd	sp, sp, #264\n"
                "\tpop	{r4, r5, r6, r7, r8, pc}\n"
                "\t.size	initThreadPool, .-initThreadPool\n"
                "\t\n"
                "\t.align	3\n"
                "\t.global	deleteThreadPool\n"
                "\t.type	deleteThreadPool, %function\n"
                "deleteThreadPool:\n"
                "\tpush	{r4, r5, r6, lr}\n"
                "\tmovw	r4, #:lower16:queueInfo\n"
                "\tmovt	r4, #:upper16:queueInfo\n"
                "\tmov	r0, r4\n"
                "\tbl	wait_spin_lock\n"
                "\tldr	r2, [r4, #8]\n"
                "\tldr	r3, [r4, #12]\n"
                "\tadd	r3, r3, #1\n"
                "\tubfx	r3, r3, #0, #9\n"
                "\tcmp	r2, r3\n"
                "\tbeq	.L71\n"
                "\tldr	r0, [r4, #12]\n"
                "\tmovw	r3, #:lower16:taskQueue\n"
                "\tldr	r1, [r4, #12]\n"
                "\tmovt	r3, #:upper16:taskQueue\n"
                "\tmov	r2, #3\n"
                "\tmov	ip, #0\n"
                "\tstr	ip, [r3, r0, lsl #3]\n"
                "\tadd	r3, r3, r1, lsl r2\n"
                "\tstr	r2, [r3, #4]\n"
                "\tldr	r3, [r4, #12]\n"
                "\tldr	r3, [r4, #12]\n"
                "\tadd	r3, r3, #1\n"
                "\tubfx	r3, r3, #0, #9\n"
                "\tstr	r3, [r4, #12]\n"
                ".L71:\n"
                "\tmovw	r5, #:lower16:workerThreads\n"
                "\tmovt	r5, #:upper16:workerThreads\n"
                "\tmov	r3, #0\n"
                "\tstr	r3, [r4]\n"
                "\tldr	r3, [r5, #4]\n"
                "\tcmp	r3, #0\n"
                "\tbeq	.L72\n"
                "\tldr	r3, [r5, #12]\n"
                "\tcmp	r3, #0\n"
                "\tbeq	.L75\n"
                "\tldr	r3, [r5, #20]\n"
                "\tcmp	r3, #0\n"
                "\tmoveq	r3, #2\n"
                "\tbeq	.L72\n"
                ".L73:\n"
                "\tmov	r4, #0\n"
                "\tmov	r6, r4\n"
                ".L74:\n"
                "\tmov	r2, #0\n"
                "\tldr	r0, [r5, r4, lsl #3]\n"
                "\tmov	r1, r2\n"
                "\tbl	waitpid\n"
                "\tstr	r6, [r5, r4, lsl #3]\n"
                "\tadd	r4, r4, #1\n"
                "\tcmp	r4, #3\n"
                "\tbne	.L74\n"
                "\tpop	{r4, r5, r6, pc}\n"
                ".L75:\n"
                "\tmov	r3, #1\n"
                ".L72:\n"
                "\tldr	r0, [r5, r3, lsl #3]\n"
                "\tmov	r1, #10\n"
                "\tbl	kill\n"
                "\tb	.L73\n"
                "\t.size	deleteThreadPool, .-deleteThreadPool\n"
                "\t\n"
                "\t.align 3\n"
                "\t.global atomic_add\n"
                "\t.type atomic_add, %function\n"
                "atomic_add:\n"
                "\tldrex r2, [r1]\n"
                "\tadd r2, r2, r0\n"
                "\tstrex r3, r2, [r1]\n"
                "\tcmp r3, #0\n"
                "\tbne atomic_add\n"
                "\tmov r0, r2\n"
                "\tbx lr\n"
                "\t\n"
                "\t.align 3\n"
                "\t.global atomic_add_post\n"
                "\t.type atomic_add_post, %function\n"
                "atomic_add_post:\n"
                "\tldrex r2, [r1]\n"
                "\tmov r12, r2\n"
                "\tadd r2, r2, r0\n"
                "\tstrex r3, r2, [r1]\n"
                "\tcmp r3, #0\n"
                "\tbne atomic_add_post\n"
                "\tmov r0, r12\n"
                "\tbx lr\n"
                "\t\n"
                "\t.align 3\n"
                "\t.global wait_spin_lock\n"
                "\t.type wait_spin_lock, %function\n"
                "wait_spin_lock:\n"
                "\tmov r2, #1\n"
                "\tldrex r1, [r0]\n"
                "\tcmp r1, #0\n"
                "\tbne wait_spin_lock_delay_start\n"
                "\tstrex r3, r2, [r0]\n"
                "\tcmp r3, #0\n"
                "\tbne wait_spin_lock\n"
                "\tbx lr\n"
                "wait_spin_lock_delay_start:\n"
                "\tmov r1, #100\n"
                "wait_spin_lock_delay_loop:\n"
                "\tsubs r1, #1\n"
                "\tbge wait_spin_lock_delay_loop\n"
                "\tb wait_spin_lock\n";
}
